### PR TITLE
Fix SG assocation with dedicated gw node in rhos

### LINKED ISSUE #227: WIth dedicated node security group is associated with incorrect VM in cloud-prepare for Openstack
**What happened**:
Security group is associated with incorrect VM in cloud-prepare for Openstack while using dedicated g/w node. Instead of the VM created for dedicated g/w node. It is getting associated with a different node. 

**What you expected to happen**:
Security groups should be associated with new node created which has the g/w node tag.

**How to reproduce it (as minimally and precisely as possible)**:
run cloud prepare rhos with dedicated g/w node set to true.

**Anything else we need to know?**:

**Environment**:
- Diagnose information (use `subctl diagnose all`):
- Gather information (use `subctl gather`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by aswinsuryan**
Fix SG assocation with dedicated gw node in rhos which was getting associated with a wrong node.

Fixes: #227 
Signed-off-by: Aswin Suryanarayanan <aswinsuryan@gmail.com>

### CODE REVIEW

File: pkg/rhos/ocpgwdeployer.go [hunk 1]
```diff
@@ -179,55 +179,73 @@ func (d *ocpGatewayDeployer) deployGWNode(gwNodes *v1.NodeList, gatewayCount int
...
-					d.InfraID+"-submariner-gw"+strconv.Itoa(i)))
+	return nil
+}
 
-				err = d.deployGateway(strconv.Itoa(i))
+func (d *ocpGatewayDeployer) tagExistingNode(groupName string, computeClient *gophercloud.ServiceClient,
+	gatewayNodesToDeploy int, reporter api.Reporter) error {
+	workerNodes, err := d.K8sClient.ListNodesWithLabel("node-role.kubernetes.io/worker")
+	if err != nil {
+		return errors.Wrap(err, fmt.Sprintf("failed to list k8s nodes in project %q", d.projectID))
```
Comment (tpantelis) [inline pkg/rhos/ocpgwdeployer.go]:
```suggestion
		return errors.Wrapf(err, "failed to list k8s nodes in project %q", d.projectID)
```

**Review by tpantelis — APPROVED** [review]

File: pkg/rhos/ocpgwdeployer.go [hunk 2]
```diff
@@ -259,6 +277,13 @@ func (d *ocpGatewayDeployer) Cleanup(reporter api.Reporter) error {
 		// If the instance name matches with d.InfraID + "-submariner-gw-", it implies that
 		// the gateway node was deployed using the OCPMachineSet API otherwise it's an existing worker node.
 		prefix := d.InfraID + "-submariner-gw-"
+
+		err = d.removeGWFirewallRules(groupName, gwNodes[i].Name, computeClient)
```
Comment (vthapar) [inline pkg/rhos/ocpgwdeployer.go]:
```suggestion
		err = d.removeFirewallRulesFromGW(groupName, gwNodes[i].Name, computeClient)
```
Current name seems to suggest we're deleting the SG itself, while we're just removing association from gw node.

**Review by vthapar — CHANGES_REQUESTED** [review]

**Review by vthapar — APPROVED** [review]

**Review by skitt — APPROVED** [review]
